apiVersion: v1
kind: Pod
metadata:
  name: ip-app-cm
spec:
  containers:
  - name: ip-app
    image: vin1093/ip-app:latest
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: prod
    - name: APP
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: app