pipeline{
    agent any
    satges{
        stage ('TEST'){
            steps{
                sh 'sleep 5'
            }
        }
         stage ('BUILD'){
            steps{
                sh 'sleep 5'
            }
        }
         stage ('DEPLOY'){
            steps{
                sh 'sleep 5'
            }
        }
    }
}